import type {Env} from "./types";
import {validateToken} from "./validation";
import {createRedirect} from "./redirect";
import {renderInvalidLinkPage,renderErrorPage} from "./pages";
import {logAccess,logError} from "./logging";
import {getInvitationById,getRfq,markAccess,updateInvitation} from "./airtable";
import {AIRTABLE_FIELDS,DEFAULT_LINK_TTL_HOURS,RFQ_FIELDS} from "./config";
const TOKEN_RE=/^[A-Za-z0-9_-]{40,64}$/;
export default {async fetch(request:Request,env:Env):Promise<Response>{try{return await route(request,env)}catch(e){logError("unhandled",e);return html(renderErrorPage(),500)}}};
async function route(req:Request,env:Env){const u=new URL(req.url); if(u.pathname==="/health"&&req.method==="GET")return json({status:"ok",service:"ctg-secure-rfq-link"}); if(u.pathname==="/api/links/create"&&req.method==="POST")return manageLink(req,env,false); if(u.pathname==="/api/links/rotate"&&req.method==="POST")return manageLink(req,env,true); if(u.pathname==="/api/links/revoke"&&req.method==="POST")return revoke(req,env); const m=u.pathname.match(/^\/r\/([A-Za-z0-9_-]+)$/); if(m&&req.method==="GET")return access(m[1],env); return new Response("Not Found",{status:404});}
async function access(token:string,env:Env){if(!TOKEN_RE.test(token)){await logAccess(token,"failure","invalid_format",null,"Token format rejected");return invalid();} const r=await validateToken(env,token); if(!r.valid){await logAccess(token,"failure",r.reason,r.invitation,r.message);return invalid();} await markAccess(env,r.invitation!.recordId); await logAccess(token,"success","valid",r.invitation,"Token validated"); return createRedirect(env,r.invitation!);}
async function manageLink(req:Request,env:Env,rotate:boolean){if(!authorized(req,env))return new Response("Unauthorized",{status:401}); const body=await safeJson(req); const id=typeof body?.rfqSupplierRecordId==="string"?body.rfqSupplierRecordId:""; const i=await getInvitationById(env,id); if(!i||!i.rfqId)return json({ok:false,error:"Invitation not found or missing RFQ"},400); if(!i.releaseEligible)return json({ok:false,error:"Invitation is not release eligible"},409); const rfq=await getRfq(env,i.rfqId); if(!rfq||rfq.status!==RFQ_FIELDS.OPEN_VALUE)return json({ok:false,error:"RFQ is not open"},409);
 const now=new Date(); const requested=Number(body?.ttlHours); const ttl=Number.isFinite(requested)&&requested>0&&requested<=168?requested:DEFAULT_LINK_TTL_HOURS; let expires=new Date(now.getTime()+ttl*3600000); if(rfq.deadline){const d=new Date(rfq.deadline); if(!isNaN(d.getTime())&&d<expires)expires=d;} if(expires<=now)return json({ok:false,error:"RFQ response deadline has passed"},409);
 const token=randomToken(); const version=Math.max(i.linkVersion||0,0)+(rotate?1:(i.linkVersion?1:1)); const fields:Record<string,unknown>={[AIRTABLE_FIELDS.TOKEN]:token,[AIRTABLE_FIELDS.LINK_VERSION]:version,[AIRTABLE_FIELDS.LINK_STATUS]:"Active",[AIRTABLE_FIELDS.ISSUED_AT]:now.toISOString(),[AIRTABLE_FIELDS.EXPIRES_AT]:expires.toISOString()}; if(rotate){fields[AIRTABLE_FIELDS.REVOKED_AT]=now.toISOString();fields[AIRTABLE_FIELDS.RESEND_COUNT]=(i.resendCount||0)+1;} else {fields[AIRTABLE_FIELDS.RESEND_COUNT]=i.resendCount||0;} if(!await updateInvitation(env,id,fields))return json({ok:false,error:"Unable to update invitation"},502); const origin=new URL(req.url).origin; return json({ok:true,url:`${origin}/r/${token}`,expiresAt:expires.toISOString(),linkVersion:version});}
async function revoke(req:Request,env:Env){if(!authorized(req,env))return new Response("Unauthorized",{status:401});const b=await safeJson(req);const id=typeof b?.rfqSupplierRecordId==="string"?b.rfqSupplierRecordId:"";if(!await getInvitationById(env,id))return json({ok:false,error:"Invitation not found"},404);const ok=await updateInvitation(env,id,{[AIRTABLE_FIELDS.LINK_STATUS]:"Revoked",[AIRTABLE_FIELDS.REVOKED_AT]:new Date().toISOString()});return json({ok},ok?200:502);}
function authorized(req:Request,env:Env){const h=req.headers.get("Authorization")||"";return !!env.WORKER_ADMIN_SECRET&&h===`Bearer ${env.WORKER_ADMIN_SECRET}`;}
function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
async function safeJson(req:Request):Promise<any>{try{return await req.json()}catch{return null}}
function invalid(){return html(renderInvalidLinkPage(),200)} function html(body:string,status:number){return new Response(body,{status,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-Robots-Tag":"noindex, nofollow","Content-Security-Policy":"default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; frame-ancestors 'none'"}})} function json(v:any,status=200){return new Response(JSON.stringify(v),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}
